resolver: nightly-2019-04-05 # GHC 8.6.4
packages:
- .
- hie-plugin-api

extra-deps:
- ./submodules/HaRe
- ./submodules/brittany
- ./submodules/cabal-helper
- ./submodules/floskell
- ./submodules/ghc-mod
- ./submodules/ghc-mod/core

- ansi-terminal-0.8.2
- butcher-1.3.2.1
- cabal-plan-0.4.0.0
- constrained-dynamic-0.1.0.0
- deque-0.2.7
- ghc-exactprint-0.5.8.2
- haddock-api-2.22.0
- haskell-lsp-0.9.0.0
- haskell-lsp-types-0.9.0.0
- haskell-src-exts-util-0.2.5
- hlint-2.1.16
- hsimport-0.8.8
- lsp-test-0.5.1.1
- monad-dijkstra-0.1.1.2@rev:1
- monad-memo-0.4.1
- multistate-0.8.0.1
- syz-0.2.0.0
- temporary-1.2.1.1
- yaml-0.8.32

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
