jobs:
- job: Linux_Stack
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      stack-def:
        YAML_FILE: stack.yaml
      stack-8.6.5:
        YAML_FILE: stack-8.6.5.yaml
      stack-8.6.4:
        YAML_FILE: stack-8.6.4.yaml
      stack-8.6.3:
        YAML_FILE: stack-8.6.3.yaml
      stack-8.6.2:
        YAML_FILE: stack-8.6.2.yaml
      stack-8.6.1:
        YAML_FILE: stack-8.6.1.yaml
      stack-8.4.4:
        YAML_FILE: stack-8.4.4.yaml
      stack-8.4.3:
        YAML_FILE: stack-8.4.3.yaml
      stack-8.4.2:
        YAML_FILE: stack-8.4.2.yaml
      stack-8.2.2:
        YAML_FILE: stack-8.2.2.yaml
  steps:
  - bash: |
      git submodule sync
      git submodule update --init
    displayName: Sync submodules
  - bash: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | \
        tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    displayName: Install stack
  - bash: |
      source .azure/linux.bashrc
      stack setup --stack-yaml $(YAML_FILE)
    displayName: Install GHC
  - bash: |
      source .azure/linux.bashrc
      stack  --stack-yaml $(YAML_FILE) --install-ghc build --only-dependencies
    displayName: Build dependencies
  - bash: |
      source .azure/linux.bashrc
      stack build --stack-yaml $(YAML_FILE)
    displayName: Build `hie`
  - bash: |
      source .azure/linux.bashrc
      stack build --stack-yaml $(YAML_FILE) --test --bench --only-dependencies
      stack install --stack-yaml $(YAML_FILE) # `hie` binary required for tests
      stack setup --stack-yaml=stack-8.6.4.yaml
      stack install --stack-yaml=stack-8.6.4.yaml cabal-install-2.4.1.0
      stack  --stack-yaml $(YAML_FILE) exec hoogle generate
      cabal v1-update
      sudo apt update
      sudo apt install z3
      stack setup --stack-yaml=stack-8.2.2.yaml
      cabal v1-install liquidhaskell-0.8.2.4 --symlink-bindir=$HOME/.local/bin -w $(stack path --stack-yaml=stack-8.2.2.yaml --compiler-exe)
    displayName: Build Test-dependencies
  - bash: |
      source .azure/linux.bashrc
      stack test --stack-yaml $(YAML_FILE)
    displayName: Run Test
